services:
  db:
    image: postgres:15-alpine
    container_name: coffeecode_db
    env_file:
      - .env
    ports:
      - "5433:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - coffeecode_network

  web:
    build: .
    container_name: coffeecode_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload
    ports:
      - "8000:8000"
    volumes:
      - .:/code
    env_file:
      - .env
    depends_on:
      - db
    networks:
      - coffeecode_network

volumes:
  postgres_data:

networks:
  coffeecode_network:
    driver: bridge
